# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  plan-common:
    - terragrunt run-all plan --terragrunt-include-dir common
  apply-common:
    - terragrunt run-all apply --terragrunt-include-dir common
  plan-prod:
    - terragrunt run-all plan --terragrunt-include-dir prod
