apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-test-server
  namespace: connectivity-test-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connectivity-test-server
  template:
    metadata:
      labels:
        app: connectivity-test-server
    spec:
      containers:
        - name: connectivity-test-server
          image: ghcr.io/blarc/connectivity-test-server:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-test-server
  namespace: connectivity-test-server
spec:
  selector:
    app: connectivity-test-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
